name: publishJar
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
jobs:

  generate-springboot:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Generate Spring Boot project
      uses: openapitools/openapi-generator-cli
      with:
        generator: spring
        input-spec: src/openapi.yaml
        output: generated-project
        artifact-id: t2authopenapi
        group-id: com.gcs
        package-name: com.gcs.t2authopenapi
        
    - name: Build Spring Boot project
      run: |
        cd generated-project
        ./mvnw clean install
        
    - name: Publish to GitHub Packages
      uses: actions/upload-artifact@v3
      with:
        name: package
        path: generated-project/target/*.jar
