name: publishJar
on:
  push:
    branches: 
      - "master"
    tags: 
      - '*'
  pull_request:
    branches: 
      - "master"
  workflow_dispatch:
jobs:

  generate-springboot:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PROJECT_PATH: generated-project

    steps:
    - uses: actions/checkout@v3

    - name: Descargar OpenAPI Generator CLI
      run: |
        wget https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/7.9.0/openapi-generator-cli-7.9.0.jar -O openapi-generator-cli.jar
    
    - name: Generar proyecto Spring Boot
      run: |
        java -jar openapi-generator-cli.jar generate -i src/openapi.yaml -g spring -o generated-project \
        --artifact-id t2authopenapi \
        --group-id "com.gcs" \
        --package-name "com.gcs.t2authopenapi" \
        --artifact-version "${GITHUB_REF}"  # Usar el tag como versión
        
    - name: Instalar Maven
      run: |
        sudo apt-get update
        sudo apt-get install maven -y

    - name: Compile JAR
      run: |    
        cd generated-project
        mvn clean package -Djar.finalName=t2authopenapi_${GITHUB_REF}
 
    - name: Verificar autenticación en GitHub Packages
      run: |
        ls -la
       
    - name: Publicar JAR en GitHub Packages
      run: |
        cd generated-project
        mvn deploy:deploy-file \
          -DgroupId=com.gcs \
          -DartifactId=t2authopenapi \
          -Dversion=${GITHUB_REF} \
          -Dtag=${GITHUB_REF} \
          -Dfile=target/t2authopenapi-${GITHUB_REF}.jar \
          -DrepositoryId=github \
          -Durl=https://maven.pkg.github.com/GabrielCruzSoto/t2-auth-openapi \
          -Dusername=${{ github.actor }} \
          -Dpassword=${{ secrets.GITHUB_TOKEN }} \
          -e

