name: publishJar
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
jobs:

  generate-springboot:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Descargar OpenAPI Generator CLI
      run: |
        wget https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/7.9.0/openapi-generator-cli-7.9.0.jar -O openapi-generator-cli.jar
    - name: Generar proyecto Spring Boot
      run: |
        java -jar openapi-generator-cli.jar generate -i src/openapi.yaml -g spring -o generated-project
        artifact-id: t2authopenapi
        group-id: com.gcs
        package-name: com.gcs.t2authopenapi
        
    - name: Construir proyecto Spring Boot
      run: |
        cd generated-project
        ./mvnw clean install
        
    - name: Publicar en GitHub Packages
      uses: actions/upload-artifact@v3
      with:
        name: package
        path: generated-project/target/*.jar
